/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.techleads.app.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Avro schema for MyMessages */
@org.apache.avro.specific.AvroGenerated
public class MyMessages extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7154701698189611250L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyMessages\",\"namespace\":\"com.techleads.app.avro\",\"doc\":\"Avro schema for MyMessages\",\"fields\":[{\"name\":\"msgId\",\"type\":\"int\",\"doc\":\"message id for MyMessages\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"message id for MyMessages\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** message id for MyMessages */
  @Deprecated public int msgId;
  /** message id for MyMessages */
  @Deprecated public java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MyMessages() {}

  /**
   * All-args constructor.
   * @param msgId message id for MyMessages
   * @param message message id for MyMessages
   */
  public MyMessages(java.lang.Integer msgId, java.lang.CharSequence message) {
    this.msgId = msgId;
    this.message = message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msgId;
    case 1: return message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msgId = (java.lang.Integer)value$; break;
    case 1: message = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'msgId' field.
   * @return message id for MyMessages
   */
  public java.lang.Integer getMsgId() {
    return msgId;
  }

  /**
   * Sets the value of the 'msgId' field.
   * message id for MyMessages
   * @param value the value to set.
   */
  public void setMsgId(java.lang.Integer value) {
    this.msgId = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return message id for MyMessages
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * message id for MyMessages
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new MyMessages RecordBuilder.
   * @return A new MyMessages RecordBuilder
   */
  public static com.techleads.app.avro.MyMessages.Builder newBuilder() {
    return new com.techleads.app.avro.MyMessages.Builder();
  }

  /**
   * Creates a new MyMessages RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MyMessages RecordBuilder
   */
  public static com.techleads.app.avro.MyMessages.Builder newBuilder(com.techleads.app.avro.MyMessages.Builder other) {
    return new com.techleads.app.avro.MyMessages.Builder(other);
  }

  /**
   * Creates a new MyMessages RecordBuilder by copying an existing MyMessages instance.
   * @param other The existing instance to copy.
   * @return A new MyMessages RecordBuilder
   */
  public static com.techleads.app.avro.MyMessages.Builder newBuilder(com.techleads.app.avro.MyMessages other) {
    return new com.techleads.app.avro.MyMessages.Builder(other);
  }

  /**
   * RecordBuilder for MyMessages instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyMessages>
    implements org.apache.avro.data.RecordBuilder<MyMessages> {

    /** message id for MyMessages */
    private int msgId;
    /** message id for MyMessages */
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.techleads.app.avro.MyMessages.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MyMessages instance
     * @param other The existing instance to copy.
     */
    private Builder(com.techleads.app.avro.MyMessages other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'msgId' field.
      * message id for MyMessages
      * @return The value.
      */
    public java.lang.Integer getMsgId() {
      return msgId;
    }

    /**
      * Sets the value of the 'msgId' field.
      * message id for MyMessages
      * @param value The value of 'msgId'.
      * @return This builder.
      */
    public com.techleads.app.avro.MyMessages.Builder setMsgId(int value) {
      validate(fields()[0], value);
      this.msgId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'msgId' field has been set.
      * message id for MyMessages
      * @return True if the 'msgId' field has been set, false otherwise.
      */
    public boolean hasMsgId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'msgId' field.
      * message id for MyMessages
      * @return This builder.
      */
    public com.techleads.app.avro.MyMessages.Builder clearMsgId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * message id for MyMessages
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * message id for MyMessages
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.techleads.app.avro.MyMessages.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * message id for MyMessages
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'message' field.
      * message id for MyMessages
      * @return This builder.
      */
    public com.techleads.app.avro.MyMessages.Builder clearMessage() {
      message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MyMessages build() {
      try {
        MyMessages record = new MyMessages();
        record.msgId = fieldSetFlags()[0] ? this.msgId : (java.lang.Integer) defaultValue(fields()[0]);
        record.message = fieldSetFlags()[1] ? this.message : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
